### PR TITLE
The second argument isn't used

### PR DESCRIPTION
**Pull request by basarat**
wouldn't have this problem if it used TypeScript

### CODE REVIEW

**Comment by p-e-w** [comment]
Does this cause an error? Has the signature changed?

**Comment by basarat** [comment]
> Does this cause an error

No. the second argument is silently ignored.

> Has the signature changed

No. This is the code in *this* repo : https://github.com/p-e-w/language-javascript-semantic/blob/master/lib/javascript-semantic-grammar.coffee#L22 the constructor doesn't use the second argument that is passed in (i.e. not even in the arg list), so why pass it.

**Comment by p-e-w** [comment]
OK, merged! Thanks for pointing this out.

**Comment by basarat** [comment]
Thanks. Btw great project as an example of code based grammar 🌹 made my life easy :)

**Pull request merged**
